# Generated by Django 6.0.5 on 2026-06-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cadastro_Clientes',
            new_name='Clientes',
        ),
        migrations.RenameModel(
            old_name='Cadastro_Logistas',
            new_name='Logistas',
        ),
        migrations.DeleteModel(
            name='Cadastro_Produtos',
        ),
    ]
