# Generated by Django 6.0.5 on 2026-06-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_contato_carrinho_itemcarrinho_metodopagamento_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logistas',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='destinatario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
