# Generated by Django 6.0.5 on 2026-06-11 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='lojista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.logistas'),
        ),
    ]
