# Generated by Django 6.0.5 on 2026-06-15 01:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_clientes_endereco_logistas_endereco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='MensagemContato',
        ),
        migrations.RenameModel(
            old_name='PasswordResetToken',
            new_name='TokenRedefinicaoSenha',
        ),
        migrations.RenameModel(
            old_name='Estoque',
            new_name='VariacaoEstoque',
        ),
        migrations.RemoveField(
            model_name='logistas',
            name='user',
        ),
        migrations.RenameField(
            model_name='tokenredefinicaosenha',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='tokenredefinicaosenha',
            old_name='used',
            new_name='utilizado',
        ),
        migrations.RenameField(
            model_name='variacaoestoque',
            old_name='produtos',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='identificador_metodo',
            field=models.CharField(help_text='Ex: Final do cartão ou identificador alternativo', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='variacaoestoque',
            unique_together={('produto', 'tamanho', 'cor')},
        ),
        migrations.RenameModel(
            old_name='Carrinho',
            new_name='CarrinhoCompra',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$', 'O telefone deve seguir o formato padrão: (84) 99999-1111')])),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'O CPF deve seguir o formato padrão: 000.000.000-00')])),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='carrinhocompra',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to='loja.cliente'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento', to='loja.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='loja.cliente'),
        ),
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
        migrations.CreateModel(
            name='Lojista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$', 'O telefone deve seguir o formato padrão: (84) 99999-1111')])),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'O CPF deve seguir o formato padrão: 000.000.000-00')])),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_lojista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='lojista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_loja', to='loja.lojista'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='lojista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.lojista'),
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Logistas',
        ),
    ]
