# Generated by Django 6.0.5 on 2026-06-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_contato_mensagemcontato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('calcas', 'Calças'), ('bermudas', 'Bermudas'), ('blusas', 'Blusas'), ('regatas', 'Regatas'), ('vestidos', 'Vestidos'), ('shorts', 'Shorts'), ('saias', 'Saias')], default='camisas', max_length=20),
        ),
    ]
