# Generated by Django 6.0.5 on 2026-06-11 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_clientes_cpf_alter_clientes_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='logistas',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
