# Generated by Django 6.0.5 on 2026-06-11 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_alter_clientes_cpf_alter_estoque_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter exatamente 11 dígitos numéricos.')]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,13}$', 'Telefone deve ter entre 10 e 13 dígitos numéricos.')]),
        ),
        migrations.AlterField(
            model_name='logistas',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter exatamente 11 dígitos numéricos.')]),
        ),
        migrations.AlterField(
            model_name='logistas',
            name='telefone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,13}$', 'Telefone deve ter entre 10 e 13 dígitos numéricos.')]),
        ),
    ]
