# Generated by Django 6.0.5 on 2026-06-12 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_clientes_cpf_alter_clientes_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve seguir o modelo: 000.000.000-00')]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(help_text='Formato: (84) 99999-1111', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$', 'Telefone deve seguir o modelo: (84) 99999-1111')]),
        ),
        migrations.AlterField(
            model_name='logistas',
            name='cpf',
            field=models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve seguir o modelo: 000.000.000-00')]),
        ),
        migrations.AlterField(
            model_name='logistas',
            name='telefone',
            field=models.CharField(help_text='Formato: (84) 99999-1111', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$', 'Telefone deve seguir o modelo: (84) 99999-1111')]),
        ),
    ]
